# https://hub.docker.com/r/linuxserver/code-server
# Port: 8443
version: "3"

services:
  code-server:
    image: linuxserver/code-server
    environment:
      - PUID=1000
      - PGID=1000
      # - PASSWORD=password
      # - HASHED_PASSWORD=
      # - SUDO_PASSWORD=password
      # - SUDO_PASSWORD_HASH=
      - DEFAULT_WORKSPACE=/config/workspace
    ports:
      - "8443:8443"
    restart: always
    volumes:
      - ./code-server/config:/config
