# https://docs.portainer.io/start/install/server/docker/linux
# Port: 9000
version: "3"

services:
  portainer:
    image: portainer/portainer-ce
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data/:/data/
